### ISSUE TITLE
Level PVM TODO

### ISSUE THREAD

**Issue by PiKeyAr** [PiKeyAr/sadx_dreamcast#115]
- [x] Station Square level PVMs
- [x] Station Square objects
- [x] Mystic Ruins level PVMs
- [x] Mystic Ruins objects
- [x] Egg Carrier level PVMs
- [x] Egg Carrier objects
- [x] Past level PVMs
- [x] Past objects
- [x] Emerald Coast level PVMs
- [x] Emerald Coast objects
- [x] Windy Valley level PVMs
- [x] Windy Valley objects
- [x] Twinkle Park level PVMs
- [x] Twinkle Park objects
- [x] Speed Highway level PVMs
- [x] Speed Highway objects
- [x] Red Mountain objects
- [x] Sky Deck level PVMs
- [x] Sky Deck objects
- [x] Lost World level PVMs
- [x] Lost World objects 1
- [x] Lost World objects 2
- [x] Ice Cap level PVMs
- [x] Ice Cap objects
- [x] Casinopolis level PVMs
- [x] Casinopolis objects
- [x] Final Egg level PVMs
- [x] Final Egg objects
- [x] Hot Shelter
- [x] Chaos 0
- [x] Chaos 2
- [x] Chaos 4
- [x] Chaos 6
- [x] Perfect Chaos
- [x] Egg Hornet
- [x] Egg Walker
- [x] Egg Viper
- [x] ZERO
- [x] E-101
- [x] E-101 R
- [x] Sky Chase 1
- [x] Sky Chase 2
- [x] Sky Chase objects
- [x] Sand Hill
- [x] Sand Hill objects
- [x] Station Square garden
- [x] Mystic Ruins garden
- [x] Egg Carrier garden
- [x] Chao objects
- [x] Chao Race
- [x] Chao Race objects
