### ISSUE TITLE
Boss lighting TODO

### ISSUE THREAD

**Issue by PiKeyAr** [PiKeyAr/sadx_dreamcast#143]
- [x] Chaos0 - 1 (base 0), 4 (specular 1)
- [x] Chaos2 - 9 (base 4), 12 (specular 5)
- [x] Chaos4 - 1 (base 0), 4 (specular 1)
- [x] Chaos6 - 9 (base 4), 12 (specular 5)
- [x] Perfect Chaos (both parts) - 9 (base 4), 12 (specular 5)
- [x] Egg Carrier 2 and Eggmobile use 5 (base 2) and 8 (specular 3)
- [x] Egg Hornet - 1 (base 0), 4 (specular 1)
- [x] Egg Viper - 1 (base 0), 4 (specular 1)
- [x] Egg Walker - 1 (base 0), 4 (specular 1)
- [x] E-101 - 1 (base 0), 4 (specular 1) with 2 (specular 0) for parts that ignore specular
- [ ] Zero, E-101MK2 - 1 (base 0), 4 (specular 1) and 2 (specular 0) for parts that ignore specular

Zero and E-101MK2 cannot be changed at the moment because those models are in .NB files.

**Comment by PiKeyAr** [comment]
I've altered all boss models except Zero and E-101MK2, the rest of the lighting inconsistencies will be addressed for each level.
